CREATE TABLE events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    provinces_id BIGINT UNSIGNED NOT NULL,
    localities_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (provinces_id) REFERENCES provinces(id) ON DELETE CASCADE,
    FOREIGN KEY (localities_id) REFERENCES localities(id) ON DELETE CASCADE
);
